# Generated by Django 5.2.6 on 2025-11-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=100, verbose_name='User Score'),
        ),
    ]
