# Generated by Django 5.2.6 on 2025-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image_alter_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
