# Generated by Django 5.2.6 on 2025-11-16 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='store name')),
                ('description', models.TextField(verbose_name='store description')),
                ('store_type', models.CharField(choices=[('PET', 'pet shop'), ('SUPPLIES', 'supplies shop')], max_length=10, verbose_name='store type')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=10, verbose_name='store status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='store_profiles/', verbose_name='profile image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store_covers/', verbose_name='cover image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('description', models.TextField(verbose_name='product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='product image')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
        ),
    ]
