# Generated by Django 5.2.6 on 2025-11-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อร้านค้า')),
                ('description', models.TextField(verbose_name='คำอธิบายร้านค้า')),
                ('store_type', models.CharField(choices=[('PET', 'ร้านขายสัตว์เลี้ยง'), ('SUPPLIES', 'ร้านขายอุปกรณ์')], max_length=10, verbose_name='ประเภทของร้าน')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ถูกปฏิเสธ')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='store_profiles/', verbose_name='รูปโปรไฟล์ร้านค้า')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store_covers/', verbose_name='รูปภาพหน้าปก')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(verbose_name='คำอธิบายสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='รูปภาพสินค้า')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='จำนวนคงคลัง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
        ),
    ]
