# Generated by Django 5.2.6 on 2025-11-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock quantity'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_covers/', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(verbose_name='store description'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_profiles/', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=10, verbose_name='store status'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('PET', 'pet shop'), ('SUPPLIES', 'supplies shop')], max_length=10, verbose_name='store type'),
        ),
    ]
