# Generated by Django 5.2.6 on 2025-12-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
    ]
