# Generated by Django 5.2.6 on 2025-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_cart_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
    ]
