# Generated by Django 5.2.6 on 2025-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_bank_details_store_payment_qr_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_proof',
            field=models.ImageField(blank=True, null=True, upload_to='shipping_proofs/', verbose_name='Shipping Proof'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for Payment'), ('PAID', 'Payment Submitted'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
