# Generated by Django 5.2.6 on 2025-12-14 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_order_shipping_proof_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='stores.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for Payment'), ('PAID', 'Payment Submitted'), ('CONFIRMED', 'Payment Confirmed'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
