# Generated by Django 5.2.6 on 2025-12-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_productreview_order_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
