# Generated by Django 5.2.6 on 2025-12-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price'),
        ),
    ]
