# Generated by Django 5.2.6 on 2025-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_orderitem_original_price_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price (Optional)'),
        ),
    ]
