# Generated by Django 5.2.6 on 2025-12-15 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_product_discount_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'author', 'order')},
        ),
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_reviews/', verbose_name='Review Image'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_reviews/', verbose_name='Review Image'),
        ),
    ]
