# Generated by Django 5.2.6 on 2025-11-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='shelter name')),
                ('description', models.TextField(verbose_name='about the shelter')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='shelter_profiles/', verbose_name='profile image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='shelter_covers/', verbose_name='cover image')),
                ('verification_document', models.FileField(upload_to='shelter_verification_docs/', verbose_name='verification document')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
