# Generated by Django 5.2.6 on 2025-11-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelterprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
