# Generated by Django 5.2.6 on 2025-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection reason'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='shelter_covers/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='description',
            field=models.TextField(verbose_name='About the shelter'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Shelter name'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='shelter_profiles/', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='verification_document',
            field=models.FileField(upload_to='shelter_verification_docs/', verbose_name='Verification document'),
        ),
    ]
