# Generated by Django 5.2.6 on 2025-12-15 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelterprofile_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_shelters', to=settings.AUTH_USER_MODEL),
        ),
    ]
