# Generated by Django 5.2.6 on 2025-11-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ikes',
            new_name='likes',
        ),
    ]
