# Generated by Django 5.2.6 on 2025-11-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='shelters.shelterprofile'),
        ),
    ]
