# Generated by Django 5.2.6 on 2025-11-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_ikes_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('none', 'ไม่มีแท็ก'), ('missing', 'สัตว์หาย'), ('adoption_update', 'อัปเดตการรับเลี้ยง'), ('qa', 'Q&A'), ('other', 'อื่นๆ'), ('care', 'เคล็ดลับการดูแลสัตว์'), ('health', 'สุขภาพ/หมอ'), ('success', 'เรื่องราวความสำเร็จ'), ('event', 'กิจกรรมรับเลี้ยง'), ('found', 'พบสัตว์หลง')], default='none', max_length=50),
        ),
    ]
