# Generated by Django 5.2.6 on 2025-12-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='animal_race',
            field=models.CharField(blank=True, choices=[('golden_retriever', 'Golden Retriever'), ('labrador_retriever', 'Labrador Retriever'), ('german_shepherd', 'German Shepherd'), ('siberian_husky', 'Siberian Husky'), ('beagle', 'Beagle'), ('border_collie', 'Border Collie'), ('australian_shepherd', 'Australian Shepherd'), ('rottweiler', 'Rottweiler'), ('doberman', 'Doberman'), ('great_dane', 'Great Dane'), ('chihuahua', 'Chihuahua'), ('pomeranian', 'Pomeranian'), ('pug', 'Pug'), ('shih_tzu', 'Shih Tzu'), ('yorkshire_terrier', 'Yorkshire Terrier'), ('corgi', 'Corgi'), ('maltese', 'Maltese'), ('domestic_shorthair', 'Domestic Shorthair'), ('domestic_longhair', 'Domestic Longhair'), ('siamese', 'Siamese'), ('persian', 'Persian'), ('maine_coon', 'Maine Coon'), ('british_shorthair', 'British Shorthair'), ('scottish_fold', 'Scottish Fold'), ('bengal', 'Bengal'), ('ragdoll', 'Ragdoll'), ('sphynx', 'Sphynx'), ('russian_blue', 'Russian Blue'), ('fennec_fox', 'Fennec Fox'), ('red_fox', 'Red Fox'), ('silver_fox', 'Silver Fox'), ('cross_fox', 'Cross Fox'), ('marble_fox', 'Marble Fox'), ('platinum_fox', 'Platinum Fox'), ('arctic_fox', 'Arctic Fox'), ('pale_fox', 'Pale Fox'), ('holland_lop', 'Holland Lop'), ('netherland_dwarf', 'Netherland Dwarf'), ('lionhead', 'Lionhead'), ('mini_rex', 'Mini Rex'), ('flemish_giant', 'Flemish Giant'), ('syrian_hamster', 'Syrian Hamster'), ('winter_white_hamster', 'Winter White Dwarf Hamster'), ('roborovski_hamster', 'Roborovski Dwarf Hamster'), ('campbells_hamster', "Campbell's Dwarf Hamster"), ('chinese_hamster', 'Chinese Hamster'), ('guinea_pig', 'Guinea Pig'), ('ferret', 'Ferret'), ('hedgehog', 'Hedgehog'), ('chinchilla', 'Chinchilla'), ('sugar_glider', 'Sugar Glider'), ('leopard_gecko', 'Leopard Gecko'), ('crested_gecko', 'Crested Gecko'), ('tokay_gecko', 'Tokay Gecko'), ('bearded_dragon', 'Bearded Dragon'), ('green_iguana', 'Green Iguana'), ('blue_tongue_skink', 'Blue-Tongue Skink'), ('corn_snake', 'Corn Snake'), ('ball_python', 'Ball Python'), ('king_snake', 'King Snake'), ('milk_snake', 'Milk Snake'), ('axolotl', 'Axolotl'), ('budgie', 'Budgie / Parakeet'), ('cockatiel', 'Cockatiel'), ('lovebird', 'Lovebird'), ('canary', 'Canary'), ('finch', 'Finch'), ('african_grey', 'African Grey Parrot'), ('macaw', 'Macaw'), ('cockatoo', 'Cockatoo'), ('sun_conure', 'Sun Conure'), ('eclectus', 'Eclectus Parrot'), ('goldfish', 'Goldfish'), ('betta', 'Betta'), ('guppy', 'Guppy'), ('discus', 'Discus'), ('arowana', 'Arowana'), ('tarantula', 'Tarantula'), ('scorpion', 'Scorpion'), ('giant_african_snail', 'Giant African Land Snail'), ('hermit_crab', 'Hermit Crab'), ('other', 'Other / Mixed')], default='other', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('fox', 'Fox'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('small_pet', 'Small Pet (Guinea Pig, Ferret, etc.)'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('fish', 'Fish / Aquatic'), ('invertebrate', 'Invertebrate'), ('other', 'Other')], default='dog', max_length=20, null=True),
        ),
    ]
