# Generated by Django 5.2.6 on 2025-12-14 16:25

import app.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('bug', 'Bug / Glitches'), ('spam', 'Spam'), ('scam', 'Scam / Fraud'), ('inappropriate', 'Inappropriate content'), ('harassment', 'Harassment / Hate'), ('animal_welfare', 'Animal welfare concern'), ('misleading', 'Misleading information'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('target_object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=10)),
                ('file', models.FileField(upload_to=app.reports.models.report_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reports.report')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='reports_rep_status_22ec20_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='reports_rep_target__7985b9_idx'),
        ),
    ]
